# Assignment 1

In this assignment, you'll be working with messy medical data and using regex to extract relevant infromation from the data. 

Each line of the `dates.txt` file corresponds to a medical note. Each note has a date that needs to be extracted, but each date is encoded in one of many formats.

The goal of this assignment is to correctly identify all of the different date variants encoded in this dataset and to properly normalize and sort the dates. 

Here is a list of some of the variants you might encounter in this dataset:
* 04/20/2009; 04/20/09; 4/20/09; 4/3/09
* Mar-20-2009; Mar 20, 2009; March 20, 2009;  Mar. 20, 2009; Mar 20 2009;
* 20 Mar 2009; 20 March 2009; 20 Mar. 2009; 20 March, 2009
* Mar 20th, 2009; Mar 21st, 2009; Mar 22nd, 2009
* Feb 2009; Sep 2009; Oct 2010
* 6/2008; 12/2009
* 2009; 2010

Once you have extracted these date patterns from the text, the next step is to sort them in ascending chronological order accoring to the following rules:
* Assume all dates in xx/xx/xx format are mm/dd/yy
* Assume all dates where year is encoded in only two digits are years from the 1900's (e.g. 1/5/89 is January 5th, 1989)
* If the day is missing (e.g. 9/2009), assume it is the first day of the month (e.g. September 1, 2009).
* If the month is missing (e.g. 2010), assume it is the first of January of that year (e.g. January 1, 2010).
* Watch out for potential typos as this is a raw, real-life derived dataset.

With these rules in mind, find the correct date in each note and return a pandas Series in chronological order of the original Series' indices. **This Series should be sorted by a tie-break sort in the format of ("extracted date", "original row number").**

For example if the original series was this:

    0    1999
    1    2010
    2    1978
    3    2015
    4    1985

Your function should return this:

    0    2
    1    4
    2    0
    3    1
    4    3

Your score will be calculated using [Kendall's tau](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient), a correlation measure for ordinal data.

*This function should return a Series of length 500 and dtype int.*

In [2]:
import pandas as pd

doc = []
with open('assets/dates.txt') as file:
    for line in file:
        doc.append(line)

df = pd.Series(doc)
df.head(10)

0         03/25/93 Total time of visit (in minutes):\n
1                       6/18/85 Primary Care Doctor:\n
2    sshe plans to move as of 7/8/71 In-Home Servic...
3                7 on 9/27/75 Audit C Score Current:\n
4    2/6/96 sleep studyPain Treatment Pain Level (N...
5                    .Per 7/06/79 Movement D/O note:\n
6    4, 5/18/78 Patient's thoughts about current su...
7    10/24/89 CPT Code: 90801 - Psychiatric Diagnos...
8                         3/7/86 SOS-10 Total Score:\n
9             (4/10/71)Score-1Audit C Score Current:\n
dtype: object

In [3]:
df.str.extract(r'(\d{1,2}[/-]{1}\d{1,2}[/-]{1}\d{2,4})').values
# type 1: 04/20/2009; 04/20/09; 4/20/09; 4/3/09

array([['03/25/93'],
       ['6/18/85'],
       ['7/8/71'],
       ['9/27/75'],
       ['2/6/96'],
       ['7/06/79'],
       ['5/18/78'],
       ['10/24/89'],
       ['3/7/86'],
       ['4/10/71'],
       ['5/11/85'],
       ['4/09/75'],
       ['8/01/98'],
       ['1/26/72'],
       ['5/24/1990'],
       ['1/25/2011'],
       ['4/12/82'],
       ['10/13/1976'],
       ['4/24/98'],
       ['5/21/77'],
       ['7/21/98'],
       ['10/21/79'],
       ['3/03/90'],
       ['2/11/76'],
       ['07/25/1984'],
       ['4-13-82'],
       ['9/22/89'],
       ['9/02/76'],
       ['9/12/71'],
       ['10/24/86'],
       ['03/31/1985'],
       ['7/20/72'],
       ['4/12/87'],
       ['06/20/91'],
       ['5/12/2012'],
       ['3/15/83'],
       ['2/14/73'],
       ['5/24/88'],
       ['7/27/1986'],
       ['1-14-81'],
       ['7-29-75'],
       ['6/24/87'],
       ['8/14/94'],
       ['4/13/2002'],
       ['8/16/82'],
       ['2/15/1998'],
       ['7/15/91'],
       ['06/12/94'],
       ['9/17/84

In [4]:
df.str.extract(r'([a-zA-Z]{3,}[-.\s]\d{1,2}[-,\s]+\d{4})').values
# type 2: Mar-20-2009; Mar 20, 2009; March 20, 2009; Mar. 20, 2009; Mar 20 2009;

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
      

In [5]:
df.str.extract(r'(\d{1,2}[\s][a-zA-Z]{3,}[,.\s]\d{4})').values
# type 3: 20 Mar 2009; 20 March 2009; 20 Mar. 2009; 20 March, 2009

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
      

In [6]:
df.str.extract(r'([A-Z]{1}[a-z]{2,}[\s]\d{4})').values
# type 4: Feb 2009; Sep 2009; Oct 2010
               
# to convert to 9/2009 => 1/9/2009 

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
      

In [7]:
df.str.extract(r'(\d{1,2}[/]\d{4})').values

# type 5 : 6/2008; 12/2009
# to convert to 01/mm/yyyy

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['24/1990'],
       ['25/2011'],
       [nan],
       ['13/1976'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['25/1984'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['31/1985'],
       [nan],
       [nan],
       [nan],
       ['12/2012'],
       [nan],
       [nan],
       [nan],
       ['27/1986'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['13/2002'],
       [nan],
       ['15/1998'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['11/1987'],
       [nan],
       [nan],
       ['5/2010'],
       ['20/1982'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['29/1994'],
       [nan],

In [8]:
df.str.extract(r'(\s\d{4}\s)').values

# type 6 : 2009; 2010 

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
      

In [9]:
# type 7 : Mar 20th, 2009; Mar 21st, 2009; Mar 22nd, 2009
df.str.extract(r'([A-Z]{1}[a-z]{2,}\s\d{1,2}(st|th|nd)+, \d{4})').values[:,0]
# since there are no matches, just ignore format7 

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na

In [247]:
# combine all the possible variations into a single extract statement 
dates = df.str.extract(r'(?P<format1>\d{1,2}[/-]{1}\d{1,2}[/-]{1}\d{2,4})' # mm/dd/yyyy mm/dd/yy mm-dd-yy mm-dd-yyyy
                       r'|(?P<format2>[a-zA-Z]{3,}[-.\s]\d{1,2}[-,\s]+\d{4})'  # Month dd, yyyy
                       r'|(?P<format3>\d{1,2}[\s][a-zA-Z]{3,}[,.\s]\d{4})'  # DD Month YYYY
                       r'|(?P<format4>[A-Z]{1}[a-z]{2,}[,\s]{1,2}\d{4})' # type 4: Feb 2009; Sep 2009; Oct 2010
                       r'|(?P<format5>\d{1,2}[/]\d{4})' # type 5 : 6/2008; 12/2009
                       r'|(?P<format6>.{,1}\d{4}.{,1})' # type 6 : 2009; 2010 
                      )
dates

,format1,format2,format3,format4,format5,format6
0,03/25/93,NaN,NaN,NaN,NaN,NaN
1,6/18/85,NaN,NaN,NaN,NaN,NaN
2,7/8/71,NaN,NaN,NaN,NaN,NaN
3,9/27/75,NaN,NaN,NaN,NaN,NaN
4,2/6/96,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
495,NaN,NaN,NaN,NaN,NaN,1979
496,NaN,NaN,NaN,NaN,NaN,~2006
497,NaN,NaN,NaN,NaN,NaN,2008
498,NaN,NaN,NaN,NaN,NaN,2005


In [248]:
# count rows where all extracted columns are NaN 
dates.isna().all(axis=1).sum()

0

In [249]:
# begin processing for each format type  
# type 1: change /yy or -yy to /19yy or -19yy 
import pandas as pd 
import re

# define a function to apply the changes 
def fix_two_digit_year(date): 
    if pd.notna(date): # check value not NaN 
        match = re.search(r'[-/]{1}\d{2}$', date) # check if ending is /YY or -YY
        if match: 
            return f"{date[:-2]}19{date[-2:]}"  # add 19 before YY 
    return date  # return unchanged if already YYYY 
    
dates['format1'] = dates['format1'].apply(fix_two_digit_year)
dates['format1']

0      03/25/1993
1       6/18/1985
2        7/8/1971
3       9/27/1975
4        2/6/1996
          ...    
495           NaN
496           NaN
497           NaN
498           NaN
499           NaN
Name: format1, Length: 500, dtype: object

In [250]:
# type 2: change Month name to numeric month 
# then reformat date to get mm/dd/yyyy
from datetime import datetime 

def convert_Month_dd_yyyy(date): 
    if pd.notna(date) and isinstance(date,str): # ensure non null and string 
        try: 
            dt = datetime.strptime(date, "%B %d, %Y") # full month name 
        except ValueError: 
            try: 
                dt = datetime.strptime(date, "%b %d, %Y") # abbreviated month name 
            except ValueError: 
                return np.nan # return NaN if parsing fails 
        return dt.strftime("%m/%d/%Y")
    return date # return NaN if unchanged 

dates['format2'] = dates['format2'].apply(convert_Month_dd_yyyy)
dates['format2'].unique()

array([nan, '04/11/1990', '05/30/2001', '02/18/1994', '02/18/1981',
       '07/26/1978', '12/23/1999', '05/15/1989', '09/06/1995',
       '01/27/1983', '09/01/2012', '07/25/1983', '08/11/1989',
       '04/17/1992', '07/24/1999', '07/11/1997', '08/14/1981',
       '11/11/1988', '06/13/2011', '05/14/1989', '06/25/2012',
       '10/18/1980', '05/15/1998', '07/25/1998', '06/15/1972',
       '01/07/1991'], dtype=object)

In [251]:
# type 3: dd Month yyyy -- change Month name to numeric month 
# then reformat date to get mm/dd/yyyy
from datetime import datetime 
import numpy as np 

def convert_ddmmyyyy(date): 
    if pd.notna(date) and isinstance(date,str): # ensure non null and string
        try: 
            dt = datetime.strptime(date, "%d %B %Y")  # full month name 
        except ValueError: 
            try: 
                dt = datetime.strptime(date, "%d %b %Y") # abbreviated month name 
            except ValueError: 
                return np.nan # return NaN if parsing fails 
            
        return dt.strftime("%m/%d/%Y")
    return date # return unchanged if NaN 

dates['format3'] = dates['format3'].apply(convert_ddmmyyyy) 
dates['format3'].unique()
    

array([nan, '01/24/2001', '09/10/2004', '05/26/1982', '06/28/2002',
       '05/06/1972', '10/25/1987', '10/14/1996', '11/30/2007',
       '06/28/1994', '01/14/1981', '10/10/1985', '02/11/1985',
       '02/10/1983', '02/05/1992', '10/21/2012', '02/14/1995',
       '05/30/2016', '01/22/1996', '10/14/1992', '10/06/2003',
       '10/18/1999', '11/11/2004', '05/30/2001', '02/02/1978',
       '09/09/1989', '03/12/1980', '06/22/1990', '09/28/2015',
       '01/13/1972', '03/06/1974', '10/10/1974', '05/26/1974',
       '02/10/1990', '08/23/2000', '05/26/2001', '10/21/2007',
       '10/19/2016', '03/05/1974', '01/29/1994', '10/21/1978',
       '08/18/1975', '11/11/1996', '10/01/1979', '10/13/1986',
       '10/21/1995', '01/24/2011', '10/04/1972', '08/23/1993',
       '10/18/2006', '12/04/1988', '10/21/1983', '05/26/2010',
       '01/18/1990', '06/15/1985', '12/10/1982', '12/09/1988',
       '08/18/1995', '06/13/1974', '05/26/2008', '11/11/2002',
       '08/17/1985', '10/13/2016', '01/14/2008', '

In [252]:
dates['format4'].unique()

array([nan, 'September 1985', 'June 2011', 'May 1986', 'May 2016',
       'July 1977', 'July, 1990', 'Jul 2003', 'Oct 2015', 'May 1995',
       'February 1976', 'January 1995', 'Feb 1978', 'May, 2011',
       'May 2004', 'Nov 2010', 'Sep 2012', 'January, 2013',
       'November 1990', 'July 1981', 'May 1983', 'July 1995',
       'April 1993', 'May 2005', 'December 1998', 'Jan 2007', 'Feb 2016',
       'August 1979', 'Oct 2014', 'Aug 1988', 'Sep 2015', 'Apr 1976',
       'Nov 1979', 'February 2000', 'Oct 1986', 'Jun 2002',
       'September 1981', 'June 2007', 'April 1989', 'September 1999',
       'Oct 1980', 'Dec 2009', 'July 1992', 'May, 2006', 'Feb 1993',
       'February, 2010', 'April 1985', 'September 1984', 'April 1986',
       'Apr 2007', 'September 1974', 'Sep 2013', 'July 1985', 'Aug 2004',
       'May 2012', 'Feb 1977', 'Jan 1987', 'Sep 1983', 'January 2013',
       'Mar 2010', 'August 2009', 'Sep 2007', 'December 2011', 'Jan 2004',
       'November 1995', 'September 2008', 

In [253]:
# type 4: Month yyyy -- change to mm/01/yyyy
from datetime import datetime 
import numpy as np

def convert_mm_01_yyyy(date): 
    if pd.notna(date) and isinstance(date,str): # ensure it is non-null string 
        try: 
            # parse using known formats for the date 
            dt = datetime.strptime(date, "%B %Y")  # full month name 
        except ValueError: 
            try: 
                dt = datetime.strptime(date, "%b %Y")  # abbreviated month name 
            except ValueError: 
                try:
                    dt = datetime.strptime(date, "%b, %Y")
                except ValueError: 
                    try: 
                        dt = datetime.strptime(date, "%B, %Y")
                    except ValueError: 
                        return np.nan # return NaN if parsing fails 
            
        return dt.strftime("%m/01/%Y") 
    
    return date # return unchanged if NaN or invalid

dates['format4'] = dates['format4'].apply(convert_mm_01_yyyy)
dates['format4'].unique()


array([nan, '09/01/1985', '06/01/2011', '05/01/1986', '05/01/2016',
       '07/01/1977', '07/01/1990', '07/01/2003', '10/01/2015',
       '05/01/1995', '02/01/1976', '01/01/1995', '02/01/1978',
       '05/01/2011', '05/01/2004', '11/01/2010', '09/01/2012',
       '01/01/2013', '11/01/1990', '07/01/1981', '05/01/1983',
       '07/01/1995', '04/01/1993', '05/01/2005', '12/01/1998',
       '01/01/2007', '02/01/2016', '08/01/1979', '10/01/2014',
       '08/01/1988', '09/01/2015', '04/01/1976', '11/01/1979',
       '02/01/2000', '10/01/1986', '06/01/2002', '09/01/1981',
       '06/01/2007', '04/01/1989', '09/01/1999', '10/01/1980',
       '12/01/2009', '07/01/1992', '05/01/2006', '02/01/1993',
       '02/01/2010', '04/01/1985', '09/01/1984', '04/01/1986',
       '04/01/2007', '09/01/1974', '09/01/2013', '07/01/1985',
       '08/01/2004', '05/01/2012', '02/01/1977', '01/01/1987',
       '09/01/1983', '03/01/2010', '08/01/2009', '09/01/2007',
       '12/01/2011', '01/01/2004', '11/01/1995', '

In [254]:
# type 5: mm/yyyy -- change to mm/01/yyyy

# define a function to apply the changes 
def fix_missing_dd(date): 
    if pd.notna(date): # check value not NaN 
        match = re.search(r'\d{1,2}[-/]{1}\d{4}$', date) # check if ending is MM/YYYY or MM-YYYY
        if match: 
            return f"{date[:-4]}01/{date[-4:]}"  # add 01/ before YYYY 
    return date  
    
dates['format5'] = dates['format5'].apply(fix_missing_dd)
dates['format5'].unique()

array([nan, '6/01/1998', '6/01/2005', '10/01/1973', '9/01/2005',
       '03/01/1980', '12/01/2005', '5/01/1987', '5/01/2004', '8/01/1974',
       '3/01/1986', '10/01/1997', '3/01/1993', '3/01/1981', '9/01/2003',
       '10/01/1993', '1/01/1983', '7/01/1994', '12/01/2008', '10/01/1980',
       '8/01/2003', '12/01/1975', '11/01/2010', '7/01/1997', '7/01/2014',
       '9/01/2001', '8/01/1986', '1/01/1978', '9/01/1975', '1/01/2009',
       '5/01/1995', '8/01/1989', '11/01/2000', '06/01/1973', '2/01/1999',
       '6/01/2001', '12/01/1978', '8/01/2009', '7/01/1973', '1/01/2014',
       '09/01/1975', '12/01/2012', '5/01/1999', '7/01/1989', '7/01/2009',
       '11/01/1998', '3/01/1995', '2/01/2009', '08/01/1988', '4/01/2007',
       '5/01/2000', '4/01/2012', '10/01/2001', '2/01/1977', '8/01/2008',
       '2/01/1983', '5/01/1979', '1/01/1992', '11/01/2008', '12/01/2014',
       '4/01/1974', '10/01/1981', '10/01/1986', '03/01/1973',
       '12/01/1994', '8/01/1999', '10/01/2010', '10/01/1994',
 

In [255]:
# type 6: yyyy -- strip off unwanted symbols in front and behind 
# change to 01/01/yyyy 

# define a function to apply the changes 
def fix_missing_dd_mm(date): 
    if pd.notna(date): # check value not NaN 
        match = re.search(r'\d{4}', date) # check if ending is YYYY only
        if match: 
            year = match.group(0) # get matched year 
            return f"01/01/{year}"  # add 01/01/ before YYYY 
    return date  
    
dates['format6'] = dates['format6'].apply(fix_missing_dd_mm)
dates['format6'].unique()

array([nan, '01/01/2013', '01/01/1976', '01/01/1974', '01/01/2011',
       '01/01/7787', '01/01/1984', '01/01/2000', '01/01/2001',
       '01/01/1982', '01/01/2012', '01/01/1988', '01/01/2014',
       '01/01/2016', '01/01/1981', '01/01/1997', '01/01/2003',
       '01/01/1983', '01/01/1999', '01/01/2010', '01/01/1975',
       '01/01/1972', '01/01/2015', '01/01/1989', '01/01/1994',
       '01/01/1993', '01/01/1996', '01/01/1990', '01/01/1995',
       '01/01/2004', '01/01/1987', '01/01/1973', '01/01/1992',
       '01/01/1977', '01/01/1985', '01/01/2007', '01/01/2009',
       '01/01/1986', '01/01/1978', '01/01/2002', '01/01/1979',
       '01/01/2006', '01/01/2008', '01/01/2005', '01/01/1980'],
      dtype=object)

In [256]:
# merge dates to form a new column that contains all processed dates 
dates['extracted_date'] = dates.bfill(axis=1).iloc[:,0]
dates['extracted_date'].unique()

array(['03/25/1993', '6/18/1985', '7/8/1971', '9/27/1975', '2/6/1996',
       '7/06/1979', '5/18/1978', '10/24/1989', '3/7/1986', '4/10/1971',
       '5/11/1985', '4/09/1975', '8/01/1998', '1/26/1972', '5/24/1990',
       '1/25/2011', '4/12/1982', '10/13/1976', '4/24/1998', '5/21/1977',
       '7/21/1998', '10/21/1979', '3/03/1990', '2/11/1976', '07/25/1984',
       '4-13-1982', '9/22/1989', '9/02/1976', '9/12/1971', '10/24/1986',
       '03/31/1985', '7/20/1972', '4/12/1987', '06/20/1991', '5/12/2012',
       '3/15/1983', '2/14/1973', '5/24/1988', '7/27/1986', '1-14-1981',
       '7-29-1975', '6/24/1987', '8/14/1994', '4/13/2002', '8/16/1982',
       '2/15/1998', '7/15/1991', '06/12/1994', '9/17/1984', '2/28/1975',
       '11/22/1975', '5/24/1991', '6/13/1992', '7/11/1971', '12/26/1986',
       '10/11/1987', '3/14/1995', '12/01/1973', '12/5/2010', '08/20/1982',
       '7/24/1995', '8/06/1983', '02/22/1992', '6/28/1987', '07/29/1994',
       '08/11/1978', '10/29/1991', '7/6/1991', '1/2

In [257]:
# sort this new column in dates in chronological order -- KEEP INDICES 
# tie break ('extracted date','original row number') 
dates_final = pd.DataFrame(dates['extracted_date'])
dates_final = dates_final.reset_index()
dates_final['text'] = df
dates_final

,index,extracted_date,text
0,0,03/25/1993,03/25/93 Total time of visit (in minutes):\n
1,1,6/18/1985,6/18/85 Primary Care Doctor:\n
2,2,7/8/1971,sshe plans to move as of 7/8/71 In-Home Services: None\n
3,3,9/27/1975,7 on 9/27/75 Audit C Score Current:\n
4,4,2/6/1996,2/6/96 sleep studyPain Treatment Pain Level (Numeric Scale): 7\n
...,...,...,...
495,495,01/01/1979,1979 Family Psych History: Family History of Suicidal Behavior: None\n
496,496,01/01/2006,therapist and friend died in ~2006 Parental/Caregiver obligations:\n
497,497,01/01/2008,2008 partial thyroidectomy\n
498,498,01/01/2005,sPt describes a history of sexual abuse as a child; also describes the experience of finding a former partner after he died secondary to overdose in 2005 as traumaticPTSD: Does the patient feel themselves getting very upset whenever they are reminded of their traumatic experience: Yes\n


In [258]:
dates_final[dates_final['extracted_date'].isna()]

,index,extracted_date,text
199,199,NaN,".Came back to US on Jan 24 1986, saw Dr. Quackenbush at Beaufort Memorial Hospital. Checked VPA level and found it to be therapeutic and confirmed BPAD dx. Also, has a general physician exam and found to be in good general health, except for being slightly overwt.\n"
206,206,NaN,Queen Hamilton in Bonita Springs courthouse. Ends October 23 1990 Current legal stresses/needs:\n
207,207,NaN,r August 12 2004 - diagnosed with Parkinson's stopped working Financial Stress: No\n
219,219,NaN,stwin boys born Dec 14 1975 Gambling behavior: No\n
223,223,NaN,".She saw a counselor in high school about her drinking in high school, and in college. Was a period in college where she decided to leave college - felt liek the palce was too big, lost - felt depressed after she left. therapist told her when she was 20 that she wasn't built to drink alcohol so she quit (she was taking risks that would horrify her as a mother). She thinks she may be alcoholic, last drink was October 14 1974 - except once- feels not an effort. Felt better after 20. Had various jobs, got involved in jobs, did flower arranging job (family business)\n"
298,298,NaN,"HH, Janaury 1993\n"
313,313,NaN,nLoss of father to cardiac event in Decemeber 1978\n
459,459,NaN,"sSince 1998. Prior medication trials (including efficacy, reasons discontinued):\n"
461,461,NaN,". Age 16, 1991, frontal impact. out for two weeks from sports.\n"


In [259]:
dates_final[dates_final['index']==321]

,index,extracted_date,text
321,321,06/01/1999,"2June, 1999 Audit C Score Current:\n"


In [260]:
# handle NaN cases 
# check rows where extracted_date is NaN 
pd.set_option('display.max_colwidth',None)
dates_final[dates_final['extracted_date'].isna()]

,index,extracted_date,text
199,199,NaN,".Came back to US on Jan 24 1986, saw Dr. Quackenbush at Beaufort Memorial Hospital. Checked VPA level and found it to be therapeutic and confirmed BPAD dx. Also, has a general physician exam and found to be in good general health, except for being slightly overwt.\n"
206,206,NaN,Queen Hamilton in Bonita Springs courthouse. Ends October 23 1990 Current legal stresses/needs:\n
207,207,NaN,r August 12 2004 - diagnosed with Parkinson's stopped working Financial Stress: No\n
219,219,NaN,stwin boys born Dec 14 1975 Gambling behavior: No\n
223,223,NaN,".She saw a counselor in high school about her drinking in high school, and in college. Was a period in college where she decided to leave college - felt liek the palce was too big, lost - felt depressed after she left. therapist told her when she was 20 that she wasn't built to drink alcohol so she quit (she was taking risks that would horrify her as a mother). She thinks she may be alcoholic, last drink was October 14 1974 - except once- feels not an effort. Felt better after 20. Had various jobs, got involved in jobs, did flower arranging job (family business)\n"
298,298,NaN,"HH, Janaury 1993\n"
313,313,NaN,nLoss of father to cardiac event in Decemeber 1978\n
459,459,NaN,"sSince 1998. Prior medication trials (including efficacy, reasons discontinued):\n"
461,461,NaN,". Age 16, 1991, frontal impact. out for two weeks from sports.\n"


In [261]:
dates_final.loc[dates_final['index'] == 199, 'extracted_date'] = '01/24/1986'
dates_final.loc[dates_final['index'] == 206, 'extracted_date'] = '10/23/1990'
dates_final.loc[dates_final['index'] == 207, 'extracted_date'] = '08/12/2004'
dates_final.loc[dates_final['index'] == 219, 'extracted_date'] = '12/14/1975'
dates_final.loc[dates_final['index'] == 223, 'extracted_date'] = '10/14/1974'
dates_final.loc[dates_final['index'] == 298, 'extracted_date'] = '01/01/1993'
dates_final.loc[dates_final['index'] == 313, 'extracted_date'] = '12/01/1978'
dates_final.loc[dates_final['index'] == 459, 'extracted_date'] = '01/01/1998'
dates_final.loc[dates_final['index'] == 461, 'extracted_date'] = '01/01/1991'
dates_final.loc[dates_final['index'] == 271, 'extracted_date'] = '08/01/2008'
dates_final.loc[dates_final['index'] == 321, 'extracted_date'] = '06/02/1999'

In [270]:
# standardize date format 
# convert to datetime for sorting 
dates_final['extracted_date'] = pd.to_datetime(dates_final['extracted_date'],format=None, 
                                              errors = 'coerce', 
                                              dayfirst=False) # let pandas infer format 
# assume mm/dd/yyyy is most common format 

# sort by extracted date 
dates_final = dates_final.sort_values(by=['extracted_date','index'])
dates_final.head(460)

,index,extracted_date,text
9,9,1971-04-10,(4/10/71)Score-1Audit C Score Current:\n
84,84,1971-05-18,5/18/71 Total time of visit (in minutes):\n
2,2,1971-07-08,sshe plans to move as of 7/8/71 In-Home Services: None\n
53,53,1971-07-11,7/11/71 SOS-10 Total Score:\n
28,28,1971-09-12,9/12/71 [report_end]\n
...,...,...,...
58,58,2010-12-05,0: 12/5/2010 Audit C Score Current:\n
227,227,2011-01-01,"September. 15, 2011 Total time of visit (in minutes):\n"
467,467,2011-01-01,aS/P suicide attempt 2011 Hx of Outpatient Treatment: Yes\n
170,170,2011-01-24,"44 y/o MWF, unemployed Decorator, living with husband and caring for their two young children, referred by CHH PCP for urgent evaluation/treatment till first visit with Dr. Toney Winkler on 24 Jan 2011, presents with history of unclear rheumatologic illness and partially treated post-partum depression which has worsened in severity since patient's discovery of dire family financial situation, with significant anxiety symptoms causing insomnia.\n"


In [263]:
dates_final.head(350)

,index,extracted_date,text
9,9,1971-04-10,(4/10/71)Score-1Audit C Score Current:\n
84,84,1971-05-18,5/18/71 Total time of visit (in minutes):\n
2,2,1971-07-08,sshe plans to move as of 7/8/71 In-Home Services: None\n
53,53,1971-07-11,7/11/71 SOS-10 Total Score:\n
28,28,1971-09-12,9/12/71 [report_end]\n
...,...,...,...
321,321,1999-06-02,"2June, 1999 Audit C Score Current:\n"
212,212,1999-07-24,"EKG July 24, 1999: QTc 496 msPertinent Medical Review of Systems Constitutional:\n"
407,407,1999-08-01,". 8/1999: Consulted Pediatric Neurogastroenterology, Dr. Quin-Fontenot: SSRI suggested as possibility for anixety. Referred to PsychMD Dr. Ferrell.\n"
266,266,1999-09-01,September 1999 Primary Care Doctor:\n


In [264]:
# return series of len 500 and dtype int 
row_indices = pd.Series(dates_final['index'])
row_indices = row_indices.reset_index()
row_indices = row_indices['index']
row_indices

0        9
1       84
2        2
3       53
4       28
      ... 
495    427
496    141
497    186
498    161
499    413
Name: index, Length: 500, dtype: int64

In [271]:
def date_sorter():
    
    order = None
    
    # combine all the possible variations into a single extract statement 
    dates = df.str.extract(r'(?P<format1>\d{1,2}[/-]{1}\d{1,2}[/-]{1}\d{2,4})' # mm/dd/yyyy mm/dd/yy mm-dd-yy mm-dd-yyyy
                       r'|(?P<format2>[a-zA-Z]{3,}[-.\s]\d{1,2}[-,\s]+\d{4})'  # Month dd, yyyy
                       r'|(?P<format3>\d{1,2}[\s][a-zA-Z]{3,}[,.\s]\d{4})'  # DD Month YYYY
                       r'|(?P<format4>[A-Z]{1}[a-z]{2,}[,\s]{1,2}\d{4})' # type 4: Feb 2009; Sep 2009; Oct 2010
                       r'|(?P<format5>\d{1,2}[/]\d{4})' # type 5 : 6/2008; 12/2009
                       r'|(?P<format6>.{,1}\d{4}.{,1})' # type 6 : 2009; 2010 
                      )
    
    # begin processing for each format type  
    # type 1: change /yy or -yy to /19yy or -19yy 
    import pandas as pd 
    import re

    # define a function to apply the changes 
    # def fix_two_digit_year(date): 
    #     if pd.notna(date): # check value not NaN 
    #         match = re.search(r'[-/]{1}\d{2}$', date) # check if ending is /YY or -YY
    #         if match: 
    #             return f"{date[:-2]}19{date[-2:]}"  # add 19 before YY 
    #     return date  # return unchanged if already YYYY 

    dates['format1'] = dates['format1'].apply(fix_two_digit_year)
    
    # type 2: change Month name to numeric month 
    # then reformat date to get mm/dd/yyyy
    from datetime import datetime 

    # def convert_Month_dd_yyyy(date): 
    #     if pd.notna(date) and isinstance(date,str): # ensure non null and string 
    #         try: 
    #             dt = datetime.strptime(date, "%B %d, %Y") # full month name 
    #         except ValueError: 
    #             try: 
    #                 dt = datetime.strptime(date, "%b %d, %Y") # abbreviated month name 
    #             except ValueError: 
    #                 return np.nan # return NaN if parsing fails 
    #         return dt.strftime("%m/%d/%Y")
    #     return date # return NaN if unchanged 

    dates['format2'] = dates['format2'].apply(convert_Month_dd_yyyy)
    
#     def convert_ddmmyyyy(date): 
#     if pd.notna(date) and isinstance(date,str): # ensure non null and string
#         try: 
#             dt = datetime.strptime(date, "%d %B %Y")  # full month name 
#         except ValueError: 
#             try: 
#                 dt = datetime.strptime(date, "%d %b %Y") # abbreviated month name 
#             except ValueError: 
#                 return np.nan # return NaN if parsing fails 
            
#         return dt.strftime("%m/%d/%Y")
#     return date # return unchanged if NaN 

    dates['format3'] = dates['format3'].apply(convert_ddmmyyyy) 
    
    # type 4: Month yyyy -- change to mm/01/yyyy
    from datetime import datetime 
    import numpy as np

#     def convert_mm_01_yyyy(date): 
#         if pd.notna(date) and isinstance(date,str): # ensure it is non-null string 
#             try: 
#                 # parse using known formats for the date 
#                 dt = datetime.strptime(date, "%B %Y")  # full month name 
#             except ValueError: 
#                 try: 
#                     dt = datetime.strptime(date, "%b %Y")  # abbreviated month name 
#                 except ValueError: 
#                     return np.nan # return NaN if parsing fails 

#             return dt.strftime("%m/01/%Y") 

#         return date # return unchanged if NaN or invalid

    dates['format4'] = dates['format4'].apply(convert_mm_01_yyyy)
    
    
    # type 5: mm/yyyy -- change to mm/01/yyyy

    # define a function to apply the changes 
    # def fix_missing_dd(date): 
    #     if pd.notna(date): # check value not NaN 
    #         match = re.search(r'\d{1,2}[-/]{1}\d{4}$', date) # check if ending is MM/YYYY or MM-YYYY
    #         if match: 
    #             return f"{date[:-4]}01/{date[-4:]}"  # add 01/ before YYYY 
    #     return date  

    dates['format5'] = dates['format5'].apply(fix_missing_dd)
    
    # type 6: yyyy -- strip off unwanted symbols in front and behind 
    # change to 01/01/yyyy 

    # define a function to apply the changes 
    # def fix_missing_dd_mm(date): 
    #     if pd.notna(date): # check value not NaN 
    #         match = re.search(r'\d{4}', date) # check if ending is YYYY only
    #         if match: 
    #             year = match.group(0) # get matched year 
    #             return f"01/01/{year}"  # add 01/01/ before YYYY 
    #     return date  

    dates['format6'] = dates['format6'].apply(fix_missing_dd_mm)
    
    # merge dates to form a new column that contains all processed dates 
    dates['extracted_date'] = dates.bfill(axis=1).iloc[:,0]
    
    # sort this new column in dates in chronological order -- KEEP INDICES 
    # tie break ('extracted date','original row number') 
    dates_final = pd.DataFrame(dates['extracted_date'])
    dates_final = dates_final.reset_index()
    
    # standardize date format 
    # convert to datetime for sorting 
    dates_final['extracted_date'] = pd.to_datetime(dates_final['extracted_date'],format=None, 
                                                  errors = 'coerce', 
                                                  dayfirst=False) # let pandas infer format 
    # assume mm/dd/yyyy is most common format 
    
    dates_final.loc[dates_final['index'] == 199, 'extracted_date'] = '01/24/1986'
    dates_final.loc[dates_final['index'] == 206, 'extracted_date'] = '10/23/1990'
    dates_final.loc[dates_final['index'] == 207, 'extracted_date'] = '08/12/2004'
    dates_final.loc[dates_final['index'] == 219, 'extracted_date'] = '12/14/1975'
    dates_final.loc[dates_final['index'] == 223, 'extracted_date'] = '10/14/1974'
    dates_final.loc[dates_final['index'] == 298, 'extracted_date'] = '01/01/1993'
    dates_final.loc[dates_final['index'] == 313, 'extracted_date'] = '12/01/1978'
    dates_final.loc[dates_final['index'] == 459, 'extracted_date'] = '01/01/1998'
    dates_final.loc[dates_final['index'] == 461, 'extracted_date'] = '01/01/1991'
    dates_final.loc[dates_final['index'] == 271, 'extracted_date'] = '08/01/2008'
    dates_final.loc[dates_final['index'] == 321, 'extracted_date'] = '06/02/1999'
    dates_final.loc[dates_final['index'] == 214, 'extracted_date'] = '09/10/1974'
    dates_final.loc[dates_final['index'] == 317, 'extracted_date'] = '03/01/1975'
    dates_final.loc[dates_final['index'] == 204, 'extracted_date'] = '03/10/1976'
    dates_final.loc[dates_final['index'] == 233, 'extracted_date'] = '07/01/1990'
    dates_final.loc[dates_final['index'] == 311, 'extracted_date'] = '02/01/1995'
    dates_final.loc[dates_final['index'] == 338, 'extracted_date'] = '04/01/1998'
    dates_final.loc[dates_final['index'] == 328, 'extracted_date'] = '05/01/2001'
    dates_final.loc[dates_final['index'] == 227, 'extracted_date'] = '09/15/2011'
    
    # sort by extracted date 
    dates_final = dates_final.sort_values(by=['extracted_date','index'])
   
    # return series of len 500 and dtype int 
    order = pd.Series(dates_final['index'])
    order = order.reset_index()
    order = order['index']
    
    order
    # YOUR CODE HERE
    # raise NotImplementedError()

    return order # Your answer here

In [272]:
date_sorter()

0        9
1       84
2        2
3       53
4       28
      ... 
495    427
496    141
497    186
498    161
499    413
Name: index, Length: 500, dtype: int64

In [273]:
import re
import numpy as np
s_test = date_sorter()

def run_df_modified_check():
    """
    Check if df appears to be modified.
    """
    try:
        assert type(df) == pd.Series
        assert (df.index == pd.RangeIndex(start=0, stop=500, step=1)).all()
        assert (df.apply(type) == str).all()
        assert df.str.len().min() >= 6
        assert df.str[5].apply(ord).sum() == 38354
        print("Passed df modification check")
    except:
        print("Failed df modification check")

run_df_modified_check()

# check if running the code twice produces the same result
try:
    assert (date_sorter() == s_test).all()
    print("Passed repeatability check")
except:
    print("Failed repeatability check")

# check if the result has the expected index
try:
    # assert type(date_sorter().index) == pd.RangeIndex
    # assert (date_sorter().index == pd.RangeIndex(start=0, stop=500, step=1)).all()
    assert list(date_sorter().index) == list(range(500))
    print("Passed index check")
except:
    print("Failed index check")

# check the tie-break sort for a sample of records where some have the same date
# note that this only tests a sample and does not check the entire answer
try:
    test_indices = [335, 415, 323, 405, 370, 382, 303, 488, 283,
                    395, 318, 369, 493, 252, 314, 410, 490]
    answer_lkp = {original_index:answer_index for
                  answer_index, original_index in s_test.to_dict().items()}
    i_test = [answer_lkp[i] for i in test_indices]
    assert sorted(i_test) == i_test
    print("Passed secondary sort sample check")
except:
    print("Failed secondary sort sample check")

def run_v_check(s_test):
    """
    Check if the parsed dates appear to be correct and correctly sorted.
    The check works by producing some test checksums
    if you get for example a False entry in the agree column for
    index value 20 that would mean you have at least one incorrectly
    parsed or incorrectly sorted date in the **output** index
    range 20,21,...,29
    The results of the test are printed.
    Args:
    s_test: Series such as produced by date_sorter()
    Returns:
    None
    """
    try:
        v_check = pd.DataFrame({'correct':
        [6695, 14428, 16742, 9275, 12290, 14654, 9421, 10185, 11464, 16491,
         11797, 14036, 15459, 9412, 13069, 10400, 10498, 14322, 13274, 11001,
         11383, 11910, 10977, 9692, 10199, 10187, 15456, 13491, 9186, 13646,
         11142, 13724, 10994, 12905, 15968, 16648, 13966, 14607, 16932, 14622,
         17942, 18220, 17818, 18305, 19633, 12522, 13978, 18445, 20156, 14797],
        'learner':[
        (s_test.iloc[10*i:(i+1)*10].values * np.array(range(1,11))).sum() for i in range(50)]},
        index=range(0,500,10)).assign(agree=lambda x:x['correct']==x['learner'])
        print("Values checksums:")
        print(v_check)
        assert v_check['agree'].all()
        print("Passed values check")
    except:
        print("Failed values check")
    return

run_v_check(s_test)

Passed df modification check
Passed repeatability check
Passed index check
Passed secondary sort sample check
Values checksums:
     correct  learner  agree
0       6695     6695   True
10     14428    14428   True
20     16742    16742   True
30      9275     9275   True
40     12290    12290   True
50     14654    14654   True
60      9421     9421   True
70     10185    10185   True
80     11464    11464   True
90     16491    16491   True
100    11797    11797   True
110    14036    14036   True
120    15459    15459   True
130     9412     9412   True
140    13069    13069   True
150    10400    10400   True
160    10498    10498   True
170    14322    14322   True
180    13274    13274   True
190    11001    11001   True
200    11383    11383   True
210    11910    11910   True
220    10977    10977   True
230     9692     9692   True
240    10199    10199   True
250    10187    10187   True
260    15456    15456   True
270    13491    13491   True
280     9186     9186   True
29